name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  staticcheck:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - run: go test ./...
